# -*- coding: utf-8 -*-
"""sp_proj_(2)_(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNr-Vlq1P-ee-bCq5ETM08epoiUVdg0c

### **Resnet-34 дообученная на Cifar-10**
"""

import torch
import torchvision
from torchvision import transforms
from tempfile import TemporaryDirectory
from torch.utils.data import random_split
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
from tqdm import tqdm
import random
from google.colab import files

device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Device: {device}")

SEED = 42
random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

g = torch.Generator()
g.manual_seed(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

import os
os.environ['PYTHONHASHSEED'] = str(SEED)

def train_model(model, full_train_loader, full_train_size, criterion, optimizer, num_epochs, device, scheduler):
  best_model_params_path = 'best_model_params.pt'
  torch.save(model.state_dict(), best_model_params_path)
  best_accuracy = 0.0

  for epoch in range(num_epochs):
    print(f'Epoch: {epoch+1}/{num_epochs}')

    for phase in ['train', 'val']:
      if phase=='train':
        model.train()
      else:
        model.eval()

      running_loss = 0.0
      running_corrects = 0

      for inputs, labels in tqdm(full_train_loader[phase]):
        inputs = inputs.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        with torch.set_grad_enabled(phase == 'train'):
          outputs = model(inputs)
          _, predictions = torch.max(outputs, 1)
          loss = criterion(outputs, labels)

          if phase=='train':
            loss.backward()
            optimizer.step()


        running_loss += loss.item() * inputs.size(0)
        running_corrects += torch.sum(predictions == labels.data)

      epoch_loss = running_loss/full_train_size[phase]
      epoch_accuracy = running_corrects.double()/full_train_size[phase]
      print(f'{phase} Loss: {epoch_loss:.4f} Acc: {epoch_accuracy:.4f}')

      if phase=='val':
        if epoch_accuracy > best_accuracy:
          best_accuracy = epoch_accuracy
          torch.save(model.state_dict(), best_model_params_path)
    scheduler.step()

  print(f'Best val Acc: {best_accuracy:.4f}')
  model.load_state_dict(torch.load(best_model_params_path, weights_only=True))
  return model

def evaluate(model, test_loader, device, criterion):
  model.eval()
  running_loss = 0.0
  correct = 0
  total = 0
  with torch.no_grad():
    for inputs, labels in tqdm(test_loader, desc="Evaluating"):
      inputs, labels = inputs.to(device), labels.to(device)
      outputs = model(inputs)
      loss = criterion(outputs, labels)
      running_loss += loss.item() * inputs.size(0)
      _, predictions = torch.max(outputs, 1)
      total+=labels.size(0)
      correct += predictions.eq(labels).sum().item()
  print()
  print(f'test_loss: {running_loss/len(test_set):.4f}, accuracy: {correct/total:.4f}\n')
  return running_loss/len(test_set), correct/total

transform_train = transforms.Compose([
    transforms.ToTensor(),
    #transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
transform_test = transforms.Compose([
    transforms.ToTensor(),
    #transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

full_train_set = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform = transform_train)
test_set = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform = transform_test)

train_set, validation_set = random_split(full_train_set, [45000, 5000], generator=g)
full_train_loader = {
    'train': torch.utils.data.DataLoader(train_set, batch_size=128, shuffle=True, pin_memory=True, generator=g),
    'val': torch.utils.data.DataLoader(validation_set, batch_size=128, shuffle=False, pin_memory=True),
}
test_loader = torch.utils.data.DataLoader(test_set, batch_size=128, shuffle=False, pin_memory=True)

full_train_size={'train': len(train_set), 'val': len(validation_set)}

model = torchvision.models.resnet34(weights='IMAGENET1K_V1')

for param in model.parameters():
        param.requires_grad = False

model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
model.fc = nn.Linear(model.fc.in_features, 10)

for param in model.conv1.parameters():
    param.requires_grad = True
for param in model.fc.parameters():
    param.requires_grad = True

for m in model.modules():
        if isinstance(m, nn.BatchNorm2d):
            for param in m.parameters():
                param.requires_grad = True

model = model.to(device)
criterion = nn.CrossEntropyLoss()

trainable_params = [p for p in model.parameters() if p.requires_grad]
optimizer = optim.SGD(trainable_params, lr=0.01, momentum=0.9, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10, 15], gamma=0.1)

model = train_model(model, full_train_loader, full_train_size, criterion, optimizer, num_epochs=20, device=device, scheduler=scheduler)
loss, accuracy = evaluate(model, test_loader, device, criterion);

import datetime
file = open('log.txt', "a", encoding = "utf-8")
dt = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
file.write(f"[{dt}] SEED: {SEED} Accuracy of model: {accuracy:.4f}\n");
file.close()

torch.save(model.state_dict(), "Model.pth")
files.download("Model.pth")

"""### **PGD атака**"""

def PGD_attack(model, image, label, epsilon, alpha, num_steps, device):
    label = label.to(device)
    image = image.to(device)

    original_image = image.clone().detach()

    noise = torch.empty_like(original_image).uniform_(-epsilon, epsilon)
    perturbed_image = original_image + noise
    perturbed_image = torch.clamp(perturbed_image, 0, 1).detach()

    for _ in range(num_steps):
        perturbed_image.requires_grad = True

        output = model(perturbed_image)
        loss = nn.functional.cross_entropy(output, label)

        model.zero_grad()
        loss.backward()

        with torch.no_grad():
            sign_data_grad = perturbed_image.grad.sign()
            perturbed_image = perturbed_image + alpha * sign_data_grad
            perturbed_image = torch.max(torch.min(perturbed_image, original_image + epsilon), original_image - epsilon)
            perturbed_image = torch.clamp(perturbed_image, 0, 1)

        perturbed_image = perturbed_image.detach()

    return perturbed_image.detach()

def PGD_test(model, device, test_loader, epsilon, alpha, num_steps):
  robust_correct = 0
  total = 0
  model.eval()

  for data, target in tqdm(test_loader, desc=f'(eps={epsilon})'):
    data, target = data.to(device), target.to(device)

    perturbed_data = PGD_attack(model, data, target, epsilon, alpha, num_steps, device)

    with torch.no_grad():
        output_adv = model(perturbed_data)
        pred = output_adv.argmax(dim=1)
        robust_correct += (pred == target).sum().item()

    total += data.size(0)

  robust_acc = robust_correct / total
  print(f"\nEps: {epsilon} | Robust Accuracy: {robust_acc:.4f}\n")

  return robust_acc

EPS = 8/255
ALPH = 1/255
NUM_STEPS = 20

acc = PGD_test(model, device, test_loader, EPS, ALPH, NUM_STEPS)

"""### **PGD защита**"""

def adversarial_train_model(model, full_train_loader, criterion, optimizer, scheduler, num_epochs, adversarial=False, eps=0.03, alpha=0.01, pgd_iters=10):
  best_model_params_path = 'best_model_params.pt'
  torch.save(model.state_dict(), best_model_params_path)
  best_accuracy = 0.0

  for epoch in range(num_epochs):
    print(f'Epoch: {epoch+1}/{num_epochs}')

    for phase in ['train', 'val']:
      if phase == 'train':
        model.train()
      else:
        model.eval()

      running_loss = 0.0
      running_corrects = 0

      for inputs, labels in tqdm(full_train_loader[phase]):
        inputs = inputs.to(device)
        labels = labels.to(device)

        if adversarial and phase == 'train':
          model.eval()
          with torch.enable_grad():
            adv_inputs = PGD_attack(model, inputs, labels, eps, alpha, pgd_iters, device)
          model.train()
          inputs = adv_inputs

        optimizer.zero_grad()

        with torch.set_grad_enabled(phase == 'train'):
          outputs = model(inputs)
          _, predictions = torch.max(outputs, 1)
          loss = criterion(outputs, labels)

          if phase == 'train':
            loss.backward()
            optimizer.step()

        running_loss += loss.item() * inputs.size(0)
        running_corrects += torch.sum(predictions == labels.data)

      epoch_loss = running_loss / full_train_size[phase]
      epoch_accuracy = running_corrects.double() / full_train_size[phase]
      print(f'{phase} Loss: {epoch_loss:.4f} Acc: {epoch_accuracy:.4f}')

      if phase == 'val':

        if epoch_accuracy > best_accuracy:
          best_accuracy = epoch_accuracy
          torch.save(model.state_dict(), best_model_params_path)
    scheduler.step()

  print(f'Best val Acc: {best_accuracy:.4f}\n')
  model.load_state_dict(torch.load(best_model_params_path, weights_only=True))
  return model

"""### **Применение PGD защиты**"""

model = torchvision.models.resnet34(weights='IMAGENET1K_V1')

for param in model.parameters():
        param.requires_grad = False

model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
model.fc = nn.Linear(model.fc.in_features, 10)

for param in model.conv1.parameters():
    param.requires_grad = True
for param in model.fc.parameters():
    param.requires_grad = True

for m in model.modules():
        if isinstance(m, nn.BatchNorm2d):
            for param in m.parameters():
                param.requires_grad = True

EPS = 8/255
ALPH = 1/255
NUM_STEPS = 20

model = model.to(device)
criterion = nn.CrossEntropyLoss()

trainable_params = [p for p in model.parameters() if p.requires_grad]
optimizer = optim.SGD(trainable_params, lr=0.01, momentum=0.9, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10, 15], gamma=0.1)

model = adversarial_train_model(model, full_train_loader, criterion, optimizer, scheduler, num_epochs=20, adversarial=True, eps=8/255, alpha=1/255, pgd_iters= 20)
loss, usual_acc = evaluate(model, test_loader, device, criterion);
robust_acc = PGD_test(model, device, test_loader, EPS, ALPH, NUM_STEPS)
print(f"PGD degradation: {accuracy-usual_acc:.4f}\n")

dt = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
file = open('log.txt', "a", encoding = "utf-8")
file.write(f"[{dt}] (PGD-based Adversarial Training) SEED: {SEED} Accuracy on usual images: {usual_acc:.4f} Accuracy degradation: {accuracy-usual_acc:.4f}\n");
file.close()

torch.save(model.state_dict(), "PGD.pth")
files.download("PGD.pth")

"""### **Label Smoothing защита**"""

def smooth_labels(labels, smoothing_param, num_classes):
    smooth_labels = labels * (1 - smoothing_param) + smoothing_param / num_classes
    return smooth_labels

def label_smoothing_train(model, full_train_loader, full_train_size, criterion, optimizer, scheduler, num_epochs, smoothing_param, device):
  best_model_params_path = 'best_model_params.pt'
  torch.save(model.state_dict(), best_model_params_path)
  best_accuracy = 0.0

  for epoch in range(num_epochs):
    print(f'Epoch: {epoch+1}/{num_epochs}')

    for phase in ['train', 'val']:
      if phase=='train':
        model.train()
      else:
        model.eval()

      running_loss = 0.0
      running_corrects = 0

      for inputs, labels in tqdm(full_train_loader[phase]):
        inputs = inputs.to(device)
        labels = labels.to(device)

        labels_one_hot = nn.functional.one_hot(labels, num_classes=10).float()
        smoothed_labels = smooth_labels(labels_one_hot, smoothing_param, 10)

        optimizer.zero_grad()

        with torch.set_grad_enabled(phase == 'train'):
          outputs = model(inputs)
          _, predictions = torch.max(outputs, 1)
          loss = criterion(outputs, smoothed_labels)

          if phase=='train':
            loss.backward()
            optimizer.step()

        running_loss += loss.item() * inputs.size(0)
        running_corrects += torch.sum(predictions == labels.data)

      epoch_loss = running_loss/full_train_size[phase]
      epoch_accuracy = running_corrects.double()/full_train_size[phase]
      print(f'{phase} Loss: {epoch_loss:.4f} Acc: {epoch_accuracy:.4f}')

      if phase=='val':
        if epoch_accuracy > best_accuracy:
          best_accuracy = epoch_accuracy
          torch.save(model.state_dict(), best_model_params_path)
      print(f"Current LR: {optimizer.param_groups[0]['lr']:.2e}")

  print(f'Best val Acc: {best_accuracy:.4f}')
  model.load_state_dict(torch.load(best_model_params_path, weights_only=True))
  return model

"""### **Применение Label Smoothing защиты**"""

model = torchvision.models.resnet34(weights='IMAGENET1K_V1')

for param in model.parameters():
        param.requires_grad = False

model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
model.fc = nn.Linear(model.fc.in_features, 10)

for param in model.conv1.parameters():
    param.requires_grad = True
for param in model.fc.parameters():
    param.requires_grad = True

for m in model.modules():
        if isinstance(m, nn.BatchNorm2d):
            for param in m.parameters():
                param.requires_grad = True

model = model.to(device)
criterion = nn.CrossEntropyLoss()

trainable_params = [p for p in model.parameters() if p.requires_grad]
optimizer = optim.SGD(trainable_params, lr=0.01, momentum=0.9, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10, 15], gamma=0.1)

model = label_smoothing_train(model, full_train_loader, full_train_size, criterion, optimizer, scheduler, num_epochs=20, smoothing_param=0.5, device=device)
loss, acc = evaluate(model, test_loader, device, criterion);
print(f"Accuracy degradation: {accuracy-acc:.4f}\n")

dt = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
file = open('log.txt', "a", encoding = "utf-8")
file.write(f"[{dt}] SEED: {SEED} LS accuracy: {acc:.4f} Accuracy degradation: {accuracy - acc:.4f}\n");
file.close()

torch.save(model.state_dict(), "LS.pth")
files.download("LS.pth")

"""### **Комбинация состязательного обучения и Label Smoothing**"""

def ls_and_pgd_train(model, full_train_loader, full_train_size, criterion, optimizer, scheduler, num_epochs, adversarial=False, eps=0.03, alpha=0.01, pgd_iters=10, smoothing_param=0.5):
  best_model_params_path = 'best_model_params.pt'
  torch.save(model.state_dict(), best_model_params_path)
  best_accuracy = 0.0

  for epoch in range(num_epochs):
    print(f'Epoch: {epoch+1}/{num_epochs}')

    for phase in ['train', 'val']:
      if phase == 'train':
        model.train()
      else:
        model.eval()

      running_loss = 0.0
      running_corrects = 0

      for inputs, labels in tqdm(full_train_loader[phase]):
        inputs = inputs.to(device)
        labels = labels.to(device)

        labels_one_hot = nn.functional.one_hot(labels, num_classes=10).float()
        smoothed_labels = smooth_labels(labels_one_hot, smoothing_param, 10)

        if adversarial and phase == 'train':
          model.eval()
          with torch.enable_grad():
            adv_inputs = PGD_attack(model, inputs, labels, eps, alpha, pgd_iters, device)
          model.train()
          inputs = adv_inputs

        optimizer.zero_grad()

        with torch.set_grad_enabled(phase == 'train'):
          outputs = model(inputs)
          _, predictions = torch.max(outputs, 1)
          loss = criterion(outputs, smoothed_labels)

          if phase == 'train':
            loss.backward()
            optimizer.step()

        running_loss += loss.item() * inputs.size(0)
        running_corrects += torch.sum(predictions == labels.data)

      epoch_loss = running_loss / full_train_size[phase]
      epoch_accuracy = running_corrects.double() / full_train_size[phase]
      print(f'{phase} Loss: {epoch_loss:.4f} Acc: {epoch_accuracy:.4f}')

      if phase == 'val':

        if epoch_accuracy > best_accuracy:
          best_accuracy = epoch_accuracy
          torch.save(model.state_dict(), best_model_params_path)
    scheduler.step()

  print(f'Best val Acc: {best_accuracy:.4f}')
  model.load_state_dict(torch.load(best_model_params_path, weights_only=True))
  return model

"""### **Применение**"""

model = torchvision.models.resnet34(weights='IMAGENET1K_V1')

for param in model.parameters():
        param.requires_grad = False

model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
model.fc = nn.Linear(model.fc.in_features, 10)

for param in model.conv1.parameters():
    param.requires_grad = True
for param in model.fc.parameters():
    param.requires_grad = True

for m in model.modules():
        if isinstance(m, nn.BatchNorm2d):
            for param in m.parameters():
                param.requires_grad = True

model = model.to(device)
criterion = nn.CrossEntropyLoss()

trainable_params = [p for p in model.parameters() if p.requires_grad]
optimizer = optim.SGD(trainable_params, lr=0.01, momentum=0.9, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10, 15], gamma=0.1)

model = ls_and_pgd_train(model, full_train_loader, full_train_size, criterion, optimizer, scheduler, num_epochs=20, adversarial=True, eps=8/255, alpha=1/255, pgd_iters= 20, smoothing_param=0.5)
loss, acc = evaluate(model, test_loader, device, criterion);
print(f"Accuracy degradation: {accuracy-acc:.4f}\n")

dt = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
file = open('log.txt', "a", encoding = "utf-8")
file.write(f"[{dt}] SEED: {SEED} PGD and LS combination accuracy: {acc:.4f} Accuracy degradation: {accuracy-acc:.4f}\n");
file.close()

torch.save(model.state_dict(), "LS_and_PGD.pth")
files.download("LS_and_PGD.pth")

"""### **Закрытие и скачивание файла логирования**"""

files.download('log.txt')